In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [3]:
my_array = np.array([1,2,3])

In [4]:
print(type(my_list))

<class 'list'>


In [5]:
print(np.array(my_list))

[1 2 3]


In [6]:
print(np.arange(0,10))

[0 1 2 3 4 5 6 7 8 9]


In [7]:
print(np.arange(0,11,2))

[ 0  2  4  6  8 10]


In [8]:
print(np.zeros(3))

[0. 0. 0.]


In [9]:
print(np.zeros((5,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [10]:
np.ones(3)

array([1., 1., 1.])

In [11]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
print(np.linspace(0,10,3))
print(np.linspace(0,5,20))
print(np.linspace(0,5,21))

[ 0.  5. 10.]
[0.         0.26315789 0.52631579 0.78947368 1.05263158 1.31578947
 1.57894737 1.84210526 2.10526316 2.36842105 2.63157895 2.89473684
 3.15789474 3.42105263 3.68421053 3.94736842 4.21052632 4.47368421
 4.73684211 5.        ]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25
 3.5  3.75 4.   4.25 4.5  4.75 5.  ]


In [13]:
print(np.random.rand(2))

[0.01758115 0.70610664]


In [14]:
print(np.random.rand(5,5))

[[0.85697022 0.61090324 0.17750035 0.42116391 0.65468516]
 [0.55866391 0.1218596  0.78052111 0.85754791 0.18492715]
 [0.77706488 0.17450074 0.88030941 0.4635316  0.81431516]
 [0.60788727 0.13836298 0.33263144 0.40803606 0.41821838]
 [0.40953296 0.53675326 0.10309183 0.64642271 0.25066579]]


In [15]:
#Same for same seed
np.random.seed(47)
print(np.random.rand(4))

[0.11348847 0.97448309 0.72873463 0.35146781]


In [16]:
print(np.random.randint(1,100))

60


In [17]:
print(np.random.randint(1,100,10))

[81  8 72 46 56 51 91 66 88 53]


In [18]:
#For seed 77
np.random.seed(77)
print(np.random.rand(4))

[0.91910903 0.6421956  0.75371223 0.13931457]


In [60]:
#Try for same seed 77
np.random.seed(77)
print(np.random.rand(4))

[0.91910903 0.6421956  0.75371223 0.13931457]


In [61]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [62]:
print(arr)
print(ranarr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[32 39 44 19 32 36 36 47 14 15]


In [63]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [64]:
ranarr.max()

47

In [65]:
ranarr.argmax()

7

In [66]:
ranarr.min()

14

In [67]:
arr = np.arange(0,11)

In [68]:
arr[1:5]

array([1, 2, 3, 4])

In [69]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [70]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [71]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
slice_of_arr = arr[0:6]
print(slice_of_arr)
print(arr)

[0 1 2 3 4 5]
[ 0  1  2  3  4  5  6  7  8  9 10]


In [73]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [74]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [75]:
#Conditional selection
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
#Check if element > 4, return True / False
bool_arr = arr>4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [77]:
#print only the True indexes
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [78]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [80]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [81]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [82]:
print(arr/arr) #Fills division by zero with nan

[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.]


C:\Users\anu\AppData\Local\Temp/ipykernel_1284/1677005437.py:1: RuntimeWarning: invalid value encountered in true_divide
  print(arr/arr) #Fills division by zero with nan


In [83]:
arr*3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [84]:
print(1/arr) #Fills with infinity

[       inf 1.         0.5        0.33333333 0.25       0.2
 0.16666667 0.14285714 0.125      0.11111111]


C:\Users\anu\AppData\Local\Temp/ipykernel_1284/3006083657.py:1: RuntimeWarning: divide by zero encountered in true_divide
  print(1/arr) #Fills with infinity


In [85]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [86]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [87]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [88]:
np.log(arr)

C:\Users\anu\AppData\Local\Temp/ipykernel_1284/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [89]:
#Summary Statistics

In [90]:
arr.sum()

45

In [91]:
arr.mean()

4.5

In [92]:
arr.max()

9

In [93]:
arr.min()

0

In [94]:
arr.var()

8.25

In [95]:
arr.std()

2.8722813232690143

In [96]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [97]:
arr_2d.shape

(3, 4)

In [98]:
arr_2d.sum(axis=0) #column-wise

array([15, 18, 21, 24])

In [99]:
arr_2d.sum(axis=1) #row-wise

array([10, 26, 42])

### Assignment 1


In [101]:
import numpy as np

In [102]:
# 1. Create an array of 10 zeros
array_zeros = np.zeros(10)
print("Array of 10 zeros:", array_zeros)

Array of 10 zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [103]:
# 2. Create an array of 10 ones
array_ones = np.ones(10)
print("Array of 10 ones:", array_ones)

Array of 10 ones: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [104]:
# 3. Create an array of 10 fives
array_fives = np.full(10, 5)
print("Array of 10 fives:", array_fives)

Array of 10 fives: [5 5 5 5 5 5 5 5 5 5]


In [105]:
# 4. Create an array of the integers from 10 to 50
array_integers = np.arange(10, 51)
print("Array of integers from 10 to 50:", array_integers)

Array of integers from 10 to 50: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [106]:
# 5. Create an array of all the even integers from 10 to 50
array_even_integers = np.arange(10, 51, 2)
print("Array of even integers from 10 to 50:", array_even_integers)

Array of even integers from 10 to 50: [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [107]:
# 6. Create a 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("3x3 matrix with values from 0 to 8:\n", matrix_3x3)

3x3 matrix with values from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [108]:
# 7. Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("3x3 identity matrix:\n", identity_matrix)

3x3 identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [109]:
# 8. Use numpy to generate a random number between 0 and 1
random_number = np.random.rand()
print("Random number between 0 and 1:", random_number)

Random number between 0 and 1: 0.7832735951745574


In [110]:
# 9. Use numpy to generate an array of 25 random numbers sampled from a standard normal distribution
random_normal_array = np.random.randn(25)
print("Array of 25 random numbers from standard normal distribution:", random_normal_array)


Array of 25 random numbers from standard normal distribution: [-0.31489931 -0.87913191 -1.09823952 -0.21677049 -1.03206435 -0.16838309
  0.5569389   0.81284184 -0.12711209 -0.15227752  0.07095881  0.01995426
 -1.12027011 -1.72720398  0.88876051 -0.43780398 -0.64161034  0.42746404
  0.83052752  1.08599978 -0.13763766 -1.40696128  1.15934812 -0.99142001
  0.1073511 ]


In [111]:
# 10. Create an array of 20 linearly spaced points between 0 and 1
linear_spaced_array = np.linspace(0, 1, 20)
print("Array of 20 linearly spaced points between 0 and 1:", linear_spaced_array)


Array of 20 linearly spaced points between 0 and 1: [0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]
