In [1]:
import numpy as np
from math import sqrt,ceil
from numpy import random

In [6]:
#1. Write a NumPy program to get the numpy version and show numpy build configuration.
print(np.__version__)

1.20.3


In [7]:
#2. Write a NumPy program to get help on the add function.
print(help(np.add))

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

In [8]:
#3. Write a NumPy program to test whether none of the elements of a given array is zero.
arr1 = np.array([1,2,3,0,3])
print(np.all(arr1))

False


In [9]:
#4. Write a NumPy program to test whether any of the elements of a given array is non-zero.
arr3 = np.array([1, 0, 0, 1, 0, 2])
print(np.any(arr3))

True


In [10]:
#5. Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number).
arr4 = np.array([1,np.inf,3,np.nan,367])
print(np.logical_or(np.isnan(arr4), np.isinf(arr4)))

[False  True False  True False]


In [11]:
#6. Write a NumPy program to test element-wise for positive or negative infinity.
arr5 = np.array([1, np.inf, 3, -np.inf, 367])
print(np.logical_or(np.isposinf(arr5), np.isneginf(arr5)))
print(np.logical_not(np.isfinite(arr5)))

[False  True False  True False]
[False  True False  True False]


In [12]:
#6. Write a NumPy program to test element-wise for positive or negative infinity.
arr5 = np.array([1, np.inf, 3, -np.inf, 367])
print(np.logical_or(np.isposinf(arr5), np.isneginf(arr5)))
print(np.logical_not(np.isfinite(arr5)))

[False  True False  True False]
[False  True False  True False]


In [13]:
#7. Write a NumPy program to test element-wise for NaN of a given array.
arr6 = np.array([1,np.nan,3,np.nan,367])
print(np.isnan(arr6))


[False  True False  True False]


In [14]:
#8. Write a NumPy program to test element-wise for complex number, real number of a given array. 
#Also test whether a given number is a scalar type or not.
print(np.iscomplex([1+1j, 1+0j, 4.5, 3, 2, 2j]))
print(np.isreal([1+1j, 1+0j, 4.5, 3, 2, 2j]))
print(np.apply_along_axis(func1d=np.isscalar,axis=0 , arr = np.array([3.1,2,4,1.1])))

[ True False False False False  True]
[False  True  True  True  True False]
False


In [16]:
#9. Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal)
#of two given arrays.
arr7 = np.random.randint(1,100,10)
arr8 = np.random.randint(1,100,10)
print("greater: ",np.greater(arr7,arr8))
print("less: ",np.less(arr7,arr8))
print("greater_equal: ",np.greater_equal(arr7,arr8))
print("less_equal: ",np.less_equal(arr7,arr8))


greater:  [False False False  True False False False False  True False]
less:  [ True  True  True False  True  True  True  True False  True]
greater_equal:  [False False False  True False False False False  True False]
less_equal:  [ True  True  True False  True  True  True  True False  True]


In [21]:
#10. Write a NumPy program to create an array with the values 1, 7, 13, 105 
#and determine the size of the memory occupied by the array.
arr9 = np.array([1, 7, 13, 105])
print("size: ", arr9.size)
print("itemsize: ", arr9.itemsize)
print("size*itemsize: ", arr9.size*arr9.itemsize)

size:  4
itemsize:  4
size*itemsize:  16


In [22]:
#11. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.
print(np.zeros(10))
print(np.ones(10))
print(np.full(10,5))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5 5 5 5 5 5 5 5 5 5]


In [25]:
#12. Write a NumPy program to create an array of the integers from 30 to 70.
print(np.arange(start=30,stop=71))

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [24]:
#13. Write a NumPy program to create an array of all the even integers from 30 to 70.
print(np.arange(start=30,stop=71,step=2))

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [27]:
#14. Write a NumPy program to create a 3x3 identity matrix.
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [26]:
#15. Write a NumPy program to generate a random number between 0 and 1.
print(np.random.random())

0.1625722527103851


In [28]:
#16. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.
print(np.random.normal(0, 1, 15))


[ 1.90819398 -0.30897075  0.58783034  0.31703796 -1.4371132  -1.1403145
 -0.55822416  0.72104451  0.04681417  1.26216771 -1.39317551 -0.91075953
  0.97361903  1.69995927 -0.38349159]


In [29]:
#17. Write a NumPy program to create a vector with values ranging from 15 to 55
#and print all values except the first and last.
print(np.arange(15, 55)[1:-1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


In [30]:
#18. Write a NumPy program to create a 3X4 array.
print(np.random.random((3,4)))
print(np.arange(1,13).reshape(3,4))


[[0.54428939 0.55141799 0.59624707 0.96391431]
 [0.75661217 0.71879165 0.1686119  0.83205985]
 [0.39356093 0.11375409 0.16306744 0.70842157]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [31]:
#19. Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.
print(np.linspace(5, 50, 10))

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [32]:
#20. Write a NumPy program to create a vector with values from 0 to 20 and change the sign of
#the numbers in the range from 9 to 15.
arr10 = np.arange(0,20)
arr10[9:16] = -1*arr10[9:16]
print(arr10)


[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19]


In [33]:
#21. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.")
print(np.random.randint(0, 11, 5))

[5 0 7 1 7]


In [34]:
#22. Write a NumPy program to multiply the values of two given vectors.
arr11 = np.random.randint(1,12,5)
arr12 = np.random.randint(1,12,5)
print(f'{arr11}*{arr12}={arr11*arr12}')

[ 6  6  6 10  9]*[2 6 9 5 8]=[12 36 54 50 72]


In [36]:
#23. Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.
print(np.random.randint(10,21,12).reshape(3,4))


[[13 16 16 12]
 [11 13 10 18]
 [17 17 17 17]]


In [35]:
#24. Write a NumPy program to find the number of rows and columns of a given matrix.")
print(np.full((3,4), np.random.random()).shape)


(3, 4)


In [37]:
#25. Write a NumPy program to create a 3x3 identity matrix, i.e. diagonal elements are 1, the rest are 0.
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [43]:
#26. Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.
arr = np.ones((10,10))
arr[1:-1,1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [44]:
#27. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.
arr14 = np.zeros((5,5))
np.fill_diagonal(arr14,np.arange(1,6))
print(arr14)

[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


In [45]:
#28. Write a NumPy program to create a 3x3x3 array filled with arbitrary values.")
arr15 = np.random.randint(low=0, high=100,size=27).reshape(3,3,3)
print(arr15)

[[[72 52 43]
  [90 83 83]
  [83 61  1]]

 [[86 56  7]
  [25 52 37]
  [16 79 23]]

 [[26 37 52]
  [74 94 62]
  [14 71  1]]]


In [46]:
#29. Write a NumPy program to compute the inner product of two given vectors.")
arr17 = np.random.randint(low=0, high=10,size=9).reshape(3,3)
arr16 = np.random.randint(low=0, high=10,size=9).reshape(3,3)
print(arr16, arr17, sep='\n')
print(np.dot(arr16,arr17))
print(np.inner(arr16,arr17))


[[2 6 9]
 [4 6 7]
 [4 2 4]]
[[8 6 5]
 [1 9 2]
 [7 5 2]]
[[ 85 111  40]
 [ 87 113  46]
 [ 62  62  32]]
[[ 97  74  62]
 [103  72  72]
 [ 64  30  46]]


In [47]:
#30. Write a NumPy program to sort a given array by row and column in ascending order.
arr20 = np.random.randint(low=0, high=30,size=9).reshape(3,3)
print(arr20)
print(np.sort(arr20,axis=0))  # Row wise
print(np.sort(arr20,axis=1))  # Column wise wise
print(np.sort(np.sort(arr20,axis=0),axis=1))  # Row the column both

[[ 9 22 25]
 [29 15 28]
 [ 9  5  7]]
[[ 9  5  7]
 [ 9 15 25]
 [29 22 28]]
[[ 9 22 25]
 [15 28 29]
 [ 5  7  9]]
[[ 5  7  9]
 [ 9 15 25]
 [22 28 29]]


In [62]:
#31. Write a NumPy program to extract all numbers from a given array which are less and greater than a specified number.
limit = 12
arr21 = np.random.randint(low=0, high=30,size=9).reshape(3,3)
print("Original: \n",arr21)
print(f"Which are greater than limit {limit}: \n", arr21> limit)
print(f"Greater than limit {limit} values:\n", arr21[arr21> limit])

Original: 
 [[ 7  0  1]
 [11  8  6]
 [20 20  8]]
Which are greater than limit 12: 
 [[False False False]
 [False False False]
 [ True  True False]]
Greater than limit 12 values:
 [20 20]


In [63]:
#32. Write a NumPy program to replace all numbers in a given array which is equal, less and greater to a given number.
#value = 11
value = 19

arr22 = arr21.copy()
print("Original:\n", arr22)

arr22[arr22 == value] = value
print("\nEqualTo\n", arr22)

arr22 = arr21.copy()
arr22[arr22 < value] = value
print("\nLessThan\n", arr22)

arr22 = arr21.copy()
arr22[arr22 > value] = value
print("\nMoreThan\n",arr22)


Original:
 [[ 7  0  1]
 [11  8  6]
 [20 20  8]]

EqualTo
 [[ 7  0  1]
 [11  8  6]
 [20 20  8]]

LessThan
 [[19 19 19]
 [19 19 19]
 [20 20 19]]

MoreThan
 [[ 7  0  1]
 [11  8  6]
 [19 19  8]]


In [67]:
#33. Write a NumPy program to create an array of equal shape and data type of a given array.
nums = np.random.randint(low=0, high=30,size=9).reshape(3,3)
print("Original:\n", nums)
temp3 = np.full_like(nums,2)
print("\nNew array:\n",temp3)
print("Shape and type: ", temp3.shape, temp3.dtype)

Original:
 [[10 14 28]
 [12  0 23]
 [13  9  8]]

New array:
 [[2 2 2]
 [2 2 2]
 [2 2 2]]
Shape and type:  (3, 3) int32


In [68]:
#34. Write a NumPy program to create a three-dimension array with shape (3,5,4) and set to a variable.
shape = (3,5,4)
arr23 = np.arange(1,shape[0]*shape[1]*shape[2]+1).reshape(shape)
print(arr23)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]
  [17 18 19 20]]

 [[21 22 23 24]
  [25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]
  [37 38 39 40]]

 [[41 42 43 44]
  [45 46 47 48]
  [49 50 51 52]
  [53 54 55 56]
  [57 58 59 60]]]


In [69]:
#35. Write a NumPy program to multiply two given arrays of same size element-by-element.
arr24 = np.random.randint(low=0, high=10,size=9).reshape(3,3)
arr25 = np.random.randint(low=0, high=10,size=9).reshape(3,3)
print(arr24, arr25, sep='\n')
print(arr24*arr25)

[[4 1 3]
 [8 6 1]
 [1 7 2]]
[[8 5 5]
 [9 6 4]
 [2 3 1]]
[[32  5 15]
 [72 36  4]
 [ 2 21  2]]
